collab-ui/collab-ui-core

docs/data/nav.json
Added the docs which were missing after moving into public repo.
@pauljeter
=> feat(docs): Added back the missing docs

scss/components/light-box.scss
Changes as per review comments on https://github.com/collab-ui/collab-ui-react/pull/2.
@pauljeter @bfbiggs @collab-ui/collab-jedi
=> feat(Lightbox): changes as per comments in collabui/react

package-lock.json, package.json, scss/components/avatar.scss, scss/components/badge.scss, scss/components/breadcrumbs.scss, scss/components/popovers.scss, scss/ng/badge.scss, scss/settings/popovers.scss, scss/tools/mixins/badges.scss, scss/tools/mixins/focus.scss, scss/tools/placeholders/typography.scss
Fixes for the web-client integration. Mainly adding prefixes and moving un prefixed classes to the ng files.
@collab-ui/collab-jedi
=> Web client fixes

scss/components/collapse-button.scss, scss/components/components.scss, scss/settings/collapse-button.scss
@pauljeter @bfbiggs @collab-ui/collab-jedi
=> feat(CollapseButton): Implementation for CollapseButton

docs/data/nav.json, scss/components/list-item.scss, scss/settings/colors.scss, scss/settings/list-item.scss
=> feat(ListItemHeader): created SparkUI styles

scss/components/avatar.scss, scss/components/composite-avatar.scss, scss/settings/avatar.scss, scss/settings/composite-avatar.scss
@pauljeter @bfbiggs @collab-ui/collab-jedi
=> feat(avatar): Sizing the avatars with ems

scss/components/avatar.scss, scss/components/list-item.scss, scss/components/space-list-item.scss, scss/settings/colors.scss, scss/settings/list-item.scss, scss/tools/mixins/list-item.scss
=> feat(SpaceListItem): added filter,search types

scss/components/button.scss, scss/settings/buttons.scss, scss/settings/colors.scss
=> feat(button): added white button style

scss/components/accordion.scss, scss/settings/list-item.scss, scss/tools/mixins/list-item.scss
=> feat(ListItem): Added styling for list-item separator

docs/data/nav.json, scss/components/button.scss, scss/components/space-list-item.scss
=>  fix(spacelist): fix header on filter type

scss/components/alert.scss
=> feat(AlertMeeting): Adjust styles for absence of snooze button.

scss/components/modal.scss, scss/components/panel.scss, scss/ng/nav-side-admin.scss, scss/ng/reveal.scss
- feat(nav-side-admin): change the padding of the logo in the nav header
- fix(modal): IE fix width of .modal-body children
- fix(panel): IE fix height of panel column flex container
=> Fix various IE flex issues

docs/data/nav.json, scss/components/button.scss, scss/settings/avatar.scss, scss/settings/colors.scss, scss/settings/icon.scss, scss/tools/mixins/buttons.scss
=>  feat(Button): added button icon class

docs/data/nav.json, scss/components/button-group.scss, scss/components/components.scss, scss/settings/button-group.scss, scss/settings/colors.scss, scss/tools/mixins/buttons.scss
=> feat(ButtonGroup): ButtonGroup implementation

scss/components/checkbox.scss, scss/components/radio.scss
=> fix(CheckBox/Radio): Fix for text wrapping on Checkbox and RadioButton

docs/data/nav.json, scss/components/components.scss, scss/components/list-item-meeting.scss, scss/settings/colors.scss, scss/settings/list-item-meeting.scss, scss/settings/settings.scss
=>  feat(ListItemMeeting): component created

docs/data/nav.json, scss/components/components.scss, scss/components/link.scss, scss/settings/colors.scss, scss/tools/mixins/link.scss, scss/tools/mixins/mixins.scss
=> feat(link): link style/examples created

scss/components/space-list-item.scss
Not a dependency to React PR, just a clean-up task.
=> fix(SpaceListMeeting): removed unused code

scss/components/datepicker.scss, scss/ng/datepicker.scss, scss/ng/ng.scss, scss/settings/date-picker.scss
Phase 1 PR for datepicker.
@pauljeter @bfbiggs @jlowery457
=> Datepicker

docs/data/nav.json, scss/components/modal.scss, scss/settings/modal.scss, scss/tools/mixins/modal.scss
=> feat(modal): update modal to Toolkit design

scss/components/components.scss, scss/components/date-picker.scss
=> feat(date-picker): Changes as per comments on DatePicker

scss/components/activity.scss, scss/components/badge.scss, scss/components/button.scss, scss/components/call-control.scss, scss/components/loading.scss, scss/components/modal.scss, scss/components/panel.scss, scss/settings/badges.scss, scss/settings/buttons.scss, scss/settings/modal.scss, scss/tools/mixins/badges.scss, scss/tools/mixins/buttons.scss, scss/tools/mixins/modal.scss
=> Button rework

.releaserc.json, docs/data/nav.json, scss/components/input.scss, scss/components/search-input.scss, scss/tools/mixins/search-input.scss, yarn.lock
=> Add styles for clear button/icon in inputs

scss/components/modal.scss, scss/tools/mixins/modal.scss
=> fix(modal): content not growing to min-height

scss/components/event-overlay.scss, scss/components/tooltip.scss, scss/settings/event-overlay.scss, scss/settings/tooltip.scss
Fixes https://app.asana.com/0/436045727210338/752149505523037
=> Beeper nub

CONTRIBUTING.md, docs/data/nav.json, scss/docs/collab-ui-docs.scss
* clarify local environment configuration
* tidy up heading margins to better visually encapsulate information
* fix small typo in layout/accordion
=> documentation(CONTRIBUTING): update contributing guidelines

scss/tools/mixins/mixins.scss, scss/tools/mixins/scrollbar.scss
=> feat(scrollbar): add base scrollbar mixin

docs/data/nav.json, scss/components/spinner.scss, scss/settings/spinner.scss
Add check className and ratio’s for circle to checkmark size.
=> feat(spinner): add check class and ratio’s for circle to checkmark size.

scss/components/avatar.scss, scss/docs/collab-ui-docs.scss, scss/settings/avatar.scss, scss/tools/mixins/avatar.scss
=> fix(avatar): apply factor sizing & fix ooo/dnd icon sizes

scss/components/modal.scss, scss/settings/modal.scss, scss/tools/mixins/modal.scss
=> feat(modal): add message class in modal header

scss/components/avatar.scss, scss/settings/avatar.scss
=> feat(avatar): add notification badge

scss/utilities/core.scss
This PR provides the blur style for the isDecrypting prop added in collab-ui-react needed for the react widgets.
=> feat(utilities): add blur style for decrypting state

scss/components/menu-overlay.scss, scss/tools/mixins/list-item.scss
Resolves collab-ui/collab-ui-react#142, collab-ui/collab-ui-react#159
=> Listitemheaderclick

docs/data/nav.json, scss/components/list-item.scss
List Items do not wrap to next row
With the `cui-list--wrap` specified, list items will wrap to the next row
- [x ] No
=> feat(list-item): add flex wrap style to lists

scss/components/modal.scss, scss/settings/media.scss, scss/settings/modal.scss
=> Modals - Update min hight and body padding

scss/tools/mixins/buttons.scss
svgs are used in Icon components, so the fill styling doesn't work with the new Icon font structure.
styling for Icon font structure
Paires with Collab-ui-angular PR: 
https://github.com/collab-ui/collab-ui-angular/pull/6
=> chore(Icon): new Icon component structure support: svg to icon font

scss/ng/ng.scss
=> feat(overlay-panel): Removing overlay-panel.scss from ng.scss file - SPARK-29316

scss/components/date-picker.scss, scss/ng/ng.scss
=> feat(date-picker): Updating date-picker scss for use in Atlas

scss/components/spinner.scss, scss/settings/spinner.scss
=> feat(spinner): adding new sizes to cui-spinner - SPARK-29316

scss/components/hero.scss, scss/elements/typography.scss, scss/settings/core.scss, scss/settings/fonts.scss
=> fix(typography): add namespace to H elements
